server:
  port: 7902
spring:
  application:
    name: provider-cart
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO      